---
- name: Download Vonage Status Panel
  get_url:
    url: https://grafana.com/api/plugins/vonage-status-panel/versions/1.0.4/download
    dest: /tmp/vonage.zip

- name: Create Grafana plugins directory
  file:
    name: /var/lib/grafana/plugins
    state: directory

- set_fact:
    vonage_plugin_path: /var/lib/grafana/plugins/Vonage-Grafana_Status_panel

- stat:
    path: "{{ vonage_plugin_path }}"
  register: vonage_plugin

- name: Unzip Vonage Status Panel
  unarchive:
    src: /tmp/vonage.zip
    remote_src: true
    dest: /var/lib/grafana/plugins/
  when: vonage_plugin.stat.exists is defined and not vonage_plugin.stat.exists

- name: Move Vonage Status Panel into place
  shell: "mv -f {{ vonage_plugin_path }}* {{ vonage_plugin_path }}"
  when: vonage_plugin.stat.exists is defined and not vonage_plugin.stat.exists
